#ifndef COMM14CUX_VERSION_H
#define COMM14CUX_VERSION_H

#define LIBCOMM14CUX_VERSION_MAJOR 2
#define LIBCOMM14CUX_VERSION_MINOR 1
#define LIBCOMM14CUX_VERSION_PATCH 3
#define LIBCOMM14CUX_VERSION "2.1.3"

#endif   
